# Generated by Django 5.0.6 on 2024-07-03 05:35

import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizness', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Subscription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('phone_number', models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '+919876543210'.", regex='^\\d{10}$')])),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('message', models.TextField()),
                ('card', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, to='bizness.card')),
            ],
        ),
    ]
