# Generated by Django 5.0.6 on 2024-07-03 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizness', '0002_subscription'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='message',
            field=models.TextField(blank=True, default=''),
        ),
    ]
