# Generated by Django 5.0.6 on 2024-07-04 06:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizness', '0003_alter_subscription_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='card',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='bizness.card'),
        ),
    ]
