# Generated by Django 5.0.6 on 2024-07-04 06:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizness', '0005_alter_subscription_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='email',
            field=models.EmailField(max_length=254),
        ),
    ]
