# Generated by Django 5.0.6 on 2024-07-04 06:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bizness', '0006_alter_subscription_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='subscription',
            name='phone_number',
            field=models.CharField(max_length=10, validators=[django.core.validators.RegexValidator(message="Phone number must be entered in the format: '9876543210'.", regex='^\\d{10}$')]),
        ),
    ]
